name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: |
          pnpm install
      - run: |
          pnpm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test Action
        id: turborepoChanges
        uses: ./
        with:
          from: HEAD^1
          working-directory: test-turborepo

      - name: Validate Outputs
        run: |
          echo packages: "${{ fromJson(steps.turborepoChanges.outputs.packages) }}"
          echo package_names: "${{ fromJson(steps.turborepoChanges.outputs.package_names) }}"
          [[ "${{ fromJson(steps.turborepoChanges.outputs.package_names) }}" && "${{ fromJson(steps.turborepoChanges.outputs.packages) }}" ]] && exit 0 || exit 1
